name: Deploy Lambdas to AWS

on:
  push:
    branches: [main]
    paths:
      - "lambdas/src/**"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          - name: Products
            path: lambdas/src/Products
          - name: Orders
            path: lambdas/src/Orders

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Install dependencies and publish
        run: |
          dotnet restore
          dotnet publish -c Release -r linux-x64 --self-contained false -o publish
        working-directory: ${{ matrix.lambda.path }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Lambda package
        run: |
          cd publish
          zip -r ../${{ matrix.lambda.name }}Function.zip .
        working-directory: ${{ matrix.lambda.path }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda.name }} \
            --zip-file fileb://${{ matrix.lambda.path }}/${{ matrix.lambda.name }}Function.zip